config/routes.rb
JackAppBase::Application.routes.draw do

  resources :relationships, :except => [ :index ]

  resources :master_tags

  resources :definitions, :except => [ :index, :show ]

  resources :usages, :except => [ :index, :show ]

  resources :entries

  resources :part_of_speeches, :path => 'parts_of_speech'

  resources :languages

  resources :word_histories, :only => [ :destroy ]

  resources :words

  devise_for :users

  root :to => 'languages#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :comments, :language_id, :part_a, :part_b, :part_c, :part_d, :part_e, :part_f, :part_of_speech_id, :primary_part, :first_form, :second_form, :third_form

  validates :part_a, :primary_part, :first_form, :second_form, :third_form, :presence => true

  before_validation :clear_empty_attrs

  belongs_to :language
  belongs_to :part_of_speech

  def self.for(item)
    where("language_id = :lang_id AND part_of_speech_id = :pos_id", { :lang_id => item.language_id, :pos_id => item.part_of_speech_id }).limit(1).first
  end

  def clear_empty_attrs
    @attributes.each do |key,value|
      self[key] = nil if value.blank?
    end
 end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  load_and_authorize_resource

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= bootstrap_form_for @entry do |f|
  = f.collection_select :language_id, Language.all, :id, :name
  = f.collection_select :part_of_speech_id, PartOfSpeech.all, :id, :name
  = f.text_field :part_a
  = f.text_field :part_b
  = f.text_field :part_c
  = f.text_field :part_d
  = f.text_field :part_e
  = f.text_field :part_f
  = f.select :primary_part, ['part_a','part_b','part_c','part_d','part_e','part_f']
  = f.text_field :first_form
  = f.text_field :second_form
  = f.text_field :third_form
  = f.text_area :comments
  = f.submit 'Save'

app/views/entries/edit.html.haml
.container
  .row
    .span4.offset4
      .well
        %h1 Edit entry
        = render 'form'
        = link_to 'cancel', @entry

app/views/entries/index.html.haml
.container
  .row
    .span12
      %h1 All entries
      %table.table.table-striped.table-condensed
        %tr
          %th Part a
          %th Part b
          %th Part c
          %th Part d
          %th Part e
          %th Part f
          %th Part of speech
          %th Language
          %th Primary part
          %th First form
          %th Second form
          %th Third form
          %th Comments
          %th
          %th
          %th

        - @entries.each do |entry|
          %tr
            %td= entry.part_a
            %td= entry.part_b
            %td= entry.part_c
            %td= entry.part_d
            %td= entry.part_e
            %td= entry.part_f
            %td= entry.part_of_speech_id
            %td= entry.language_id
            %td= entry.primary_part
            %td= entry.first_form
            %td= entry.second_form
            %td= entry.third_form
            %td= entry.comments
            %td= link_to 'Show', entry
            %td= link_to 'Edit', edit_entry_path(entry)
            %td= link_to 'Destroy', entry, :confirm => 'Are you sure?', :method => :delete

app/views/entries/new.html.haml
.container
  .row
    .span4.offset4
      .well
        %h1 New entry
        = render 'form'
        = link_to 'cancel', entries_path

app/views/entries/show.html.haml
.container
  .row
    .span3
      .well
        %h1
          = @entry.language.name 
          = @entry.part_of_speech.name.pluralize
    .span9
      %p
        %b Part a:
        = @entry.part_a
      %p
        %b Part b:
        = @entry.part_b
      %p
        %b Part c:
        = @entry.part_c
      %p
        %b Part d:
        = @entry.part_d
      %p
        %b Part e:
        = @entry.part_e
      %p
        %b Part f:
        = @entry.part_f
      %p
        %b Primary part:
        = @entry.primary_part
      %p
        %b First form:
        = @entry.first_form
      %p
        %b Second form:
        = @entry.second_form
      %p
        %b Third form:
        = @entry.third_form
      %p
        %b Comments:
        = @entry.comments

      = link_to 'Edit', edit_entry_path(@entry)
      \|
      = link_to 'Back', entries_path