config/routes.rb
JackAppBase::Application.routes.draw do

  resources :relationships, :except => [ :index ]

  resources :master_tags

  resources :definitions, :except => [ :index, :show ]

  resources :usages, :except => [ :index, :show ]

  resources :entries

  resources :part_of_speeches, :path => 'parts_of_speech'

  resources :languages

  resources :word_histories, :only => [ :destroy ]

  resources :words

  devise_for :users

  root :to => 'languages#index'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :relationship_type_id, :user_id, :word_a_id, :word_b_id

  validates :relationship_type_id, :user_id, :word_a_id, :word_b_id, :presence => true

  belongs_to :relationship_type
  belongs_to :user
  belongs_to :word_a, :class_name => 'Word'
  belongs_to :word_b, :class_name => 'Word'

end

app/models/relationship_type.rb
class RelationshipType < ActiveRecord::Base
  attr_accessible :description, :name, :pictogram

  has_many :relationships, :dependent => :destroy
  has_many :children, :through => :relationships, :source => :word_b
  has_many :parents, :through => :relationships, :source => :word_a

  def children_of(item)
    relationships.where(:word_a_id => item.id)
  end

  def parents_of(item)
    relationships.where(:word_b_id => item.id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  load_and_authorize_resource

  # GET /relationships/1
  # GET /relationships/1.json
  def show
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/new
  # GET /relationships/new.json
  def new
    @relationship = Relationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Relationship.new(params[:relationship])

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render json: @relationship, status: :created, location: @relationship }
      else
        format.html { render action: "new" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relationships/1
  # PUT /relationships/1.json
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to relationships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.haml
= bootstrap_form_for @relationship do |f|
  = f.collection_select :word_a_id, Word.all, :id, :first_form
  = f.collection_select :word_b_id, Word.all, :id, :first_form
  = f.collection_select :relationship_type_id, RelationshipType.all, :id, :name
  = f.hidden_field :user_id, :value => current_user.id
  = f.submit 'Save'

app/views/relationships/edit.html.haml
.container
  .row
    .span4.offset4
      .well
        %h1 Editing relationship
        = render 'form'
        = link_to 'cancel', @relationship

app/views/relationships/index.html.haml
%h1 Listing relationships

%table
  %tr
    %th Word a
    %th Word b
    %th Relationship type
    %th User
    %th
    %th
    %th

  - @relationships.each do |relationship|
    %tr
      %td= relationship.word_a_id
      %td= relationship.word_b_id
      %td= relationship.relationship_type_id
      %td= relationship.user_id
      %td= link_to 'Show', relationship
      %td= link_to 'Edit', edit_relationship_path(relationship)
      %td= link_to 'Destroy', relationship, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Relationship', new_relationship_path

app/views/relationships/new.html.haml
.container
  .row
    .span4.offset4
      .well
        %h1 New relationship
        = render 'form'
        = link_to 'cancel', words_path

app/views/relationships/show.html.haml
.container
  .row
    .span9.offset3
      %p
        = link_to @relationship.word_a.first_form, @relationship.word_a
        = @relationship.relationship_type.pictogram
        = link_to @relationship.word_b.first_form, @relationship.word_b
      %p
        Relationship created by
        = @relationship.user.email