config/routes.rb
JackAppBase::Application.routes.draw do

  resources :relationships, :except => [ :index ]

  resources :master_tags

  resources :definitions, :except => [ :index, :show ]

  resources :usages, :except => [ :index, :show ]

  resources :entries

  resources :part_of_speeches, :path => 'parts_of_speech'

  resources :languages

  resources :word_histories, :only => [ :destroy ]

  resources :words

  devise_for :users

  root :to => 'languages#index'

end

app/models/master_tag.rb
class MasterTag < ActiveRecord::Base
  attr_accessible :en, :fr

  validates :en, :presence => true

  has_and_belongs_to_many :words

  default_scope :order => 'en ASC'

end

app/controllers/master_tags_controller.rb
class MasterTagsController < ApplicationController
  load_and_authorize_resource

  # GET /master_tags
  # GET /master_tags.json
  def index
    @master_tags = MasterTag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @master_tags }
    end
  end

  # GET /master_tags/1
  # GET /master_tags/1.json
  def show
    @master_tag = MasterTag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @master_tag }
    end
  end

  # GET /master_tags/new
  # GET /master_tags/new.json
  def new
    @master_tag = MasterTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @master_tag }
    end
  end

  # GET /master_tags/1/edit
  def edit
    @master_tag = MasterTag.find(params[:id])
  end

  # POST /master_tags
  # POST /master_tags.json
  def create
    @master_tag = MasterTag.new(params[:master_tag])

    respond_to do |format|
      if @master_tag.save
        format.html { redirect_to @master_tag, notice: 'Master tag was successfully created.' }
        format.json { render json: @master_tag, status: :created, location: @master_tag }
      else
        format.html { render action: "new" }
        format.json { render json: @master_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /master_tags/1
  # PUT /master_tags/1.json
  def update
    @master_tag = MasterTag.find(params[:id])

    respond_to do |format|
      if @master_tag.update_attributes(params[:master_tag])
        format.html { redirect_to @master_tag, notice: 'Master tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @master_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_tags/1
  # DELETE /master_tags/1.json
  def destroy
    @master_tag = MasterTag.find(params[:id])
    @master_tag.destroy

    respond_to do |format|
      format.html { redirect_to master_tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/master_tags_helper.rb
module MasterTagsHelper
end

app/views/master_tags/_form.html.haml
= bootstrap_form_for @master_tag do |f|
  = f.text_field :en
  = f.text_field :fr
  = f.submit 'Save'

app/views/master_tags/_master_tag.html.haml
%span.label.label-inverse= link_to master_tag.en, master_tag

app/views/master_tags/_menu.html.haml
%ul.nav.nav-list
  - for tag in MasterTag.all
    %li= link_to tag.en, tag

app/views/master_tags/edit.html.haml
.container
  .row
    .span4.offset4
      .well
        %h1 Edit tag
        = render 'form'
        = link_to 'cancel', @master_tag

app/views/master_tags/index.html.haml
.container
  .row
    .span3
      %h1 Tags
      = render 'menu'
    .span9
      %table.table.table-condensed.table-striped
        %tr
          %th En
          %th Fr
          %th
          %th
          %th

        - @master_tags.each do |master_tag|
          %tr
            %td= master_tag.en
            %td= master_tag.fr
            %td= link_to 'Show', master_tag
            %td= link_to 'Edit', edit_master_tag_path(master_tag)
            %td= link_to 'Destroy', master_tag, :confirm => 'Are you sure?', :method => :delete

app/views/master_tags/new.html.haml
.container
  .row
    .span4.offset4
      .well
        %h1 New tag
        = render 'form'
        = link_to 'cancel', master_tags_path

app/views/master_tags/show.html.haml
.container
  .row
    .span3
      .well
        %h1= @master_tag.en
        %p= @master_tag.fr
    .span9
      %ul
        - for word in @master_tag.words do
          %li= link_to word.first_form, word