config/routes.rb
JackAppBase::Application.routes.draw do

  resources :relationships, :except => [ :index ]

  resources :master_tags

  resources :definitions, :except => [ :index, :show ]

  resources :usages, :except => [ :index, :show ]

  resources :entries

  resources :part_of_speeches, :path => 'parts_of_speech'

  resources :languages

  resources :word_histories, :only => [ :destroy ]

  resources :words

  devise_for :users

  root :to => 'languages#index'

end

app/views/layouts/application.html.haml
:erb
  <!DOCTYPE html>
%html
  %head
    %title Talk To Me!
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            .row
              .span12
                %a.brand{:href => '/'} Talk To Me!
                %ul.nav
                  %li= link_to 'words', words_path
                  %li= link_to 'languages', languages_path
                %ul.nav.pull-right
                  %li= link_to 'Sign in', new_user_session_path unless user_signed_in?
                  %li= link_to 'Sign up', new_user_registration_path unless user_signed_in?
                  %li= link_to "Sign out #{current_user.email}", destroy_user_session_path, :method => :delete if user_signed_in?
    .container
      .row
        .span4.offset4
          - if notice
            .alert.alert-success.center
              = notice
          - if alert
            .alert.alert-error.center
              = alert
    = yield
    .container
      .row
        .span12
          %hr
          %p This project is brought to you independently by the Volunteers of #{link_to 'Peace Corps Senegal', 'http://www.pcsenegal.org'}. It in no way represents the United States Peace Corps, its staff, or the American people.
        - if Rails.env.development?
          .span12
            = debug(params)